import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar";
import CTA from "./_components/cta-section";
import Footer from "./_components/footer-section";
import localFont from "next/font/local";
import ZohoDeskWidget from "./_components/ZohoDeskWidget";
const myFont = localFont({
  src: [
    {
      path: "../public/fonts/BrittiSansTrial-Regular-BF6757bfd47ffbf.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/BrittiSansTrial-Bold-BF6757bfd4a96ed.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-britti",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} antialiased`}>
        <Navbar />
        {children}
        {/* <ZohoDeskWidget /> */}
        <CTA />
        <Footer />
      </body>
    </html>
  );
}
